
import {NavBar, Footer} from "../components/componentsindex";
import "./globals.css";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
        <header><NavBar/></header>
        {children}
        <footer><Footer/></footer>
      </body>
    </html>
  )
}
